x-veld:
  code:
      description: "custom evaluation logic for word2vec, fasttext and glove models"
      topics:
        - "NLP"
        - "Machine Learning"
        - "word embeddings"
        - "evaluation"

    inputs:
      - volume: /veld/input/1/
        file_formats: 
          - "word2vec model"
          - "fasttext model"
        contents:
          - "Machine learning model"
          - "NLP model"
          - "word embeddings model"
      - volume: /veld/input/2/
        file_formats: "yaml"
        contents:
          - "NLP evaluation data"
          - "NLP data"

    outputs:
      volume: /veld/output/
      file_formats: 
        - "yaml"
        - "txt"
      contents: 
        - "evaluation results"
        - "Machine learning evaluation results"
        - "NLP evaluation results"
        - "word embeddings evaluation results"
        - "logs"

    environment:
      in_1_model_file:
        description: "model file or folder"
        type: file
        volume: /veld/input/1/
      in_1_model_metadata_file:
        description: "metadata yaml file"
        type: file
        volume: /veld/input/1/
        optional: true
      in_2_eval_data_file:
        description: "evaluation yaml file"
        type: file
        volume: /veld/input/2/

services:
  veld:
    build: .
    volumes:
      - ./volumes/input/1/:/veld/input/1/
      - ./volumes/input/2/:/veld/input/2/
      - ./volumes/output/:/veld/output/
      - ./src/:/veld/executable/
    working_dir: /veld/executable/
    command: python /veld/executable/eval_and_report.py
    environment:
      in_1_model_file: null
      in_1:model_metadata_file: null 
      in_2_eval_data_file: null

