x-veld:
  code:
    description: ""
    topics:
      - ""
    additional:
      foo:
        bar:

    inputs:
      - description: ""
        volume: /veld/input/
        environment_file_vars: 
          in_evaluation_summary_file:
            description: "summary of the custom evaluation logic on word embeddings"
            file_type: "yaml"

    environment_config_vars:
      foo:
        description: ""
        var_type: ""
        optional: ""
        default: ""

services:
  veld_analyse_evaluation:
    build: 
      context: .
      dockerfile: ./build_analyse.dockerfile
    command: jupyter notebook --allow-root --ip='*' --NotebookApp.token='' --NotebookApp.password=''
    ports:
      - 8888:8888
    volumes:
      - ./src/analyse/:/veld/code/:z
    environment:
      in_evaluation_summary_file: null

