
x-veld:
  executable:

    inputs:
      - volume: /veld/input/1/
        type: "word2vec model"
        content:
          - "NLP model"
          - "word embeddings model"
      - volume: /veld/input/2/
        type: "yaml"
        content:
          - "NLP evaluation data"
          - "NLP data"

    outputs:
      volume: /veld/output/
      type: 
        - "yaml"
        - "txt"
      content: "NLP evaluation"

    environment:
      model_path:
        description: "path to word2vec model file."
        type: string
        prefix: "/veld/input/1/"
      model_metadata_path:
        description: "path to metadata yaml file."
        type: string
        prefix: "/veld/input/1/"
      eval_data_path:
        description: "path to evaluation yaml file."
        type: string
        prefix: "/veld/input/2/"
      eval_results_folder:
        description: "path to folder where summary and logs will be saved to."
        type: string
        prefix: "/veld/output/"

    chain_template: # you can copy this template below into a new chain veld.yaml for using this executable
      x-veld:
        chain:
      services:
        veld:
          extends:
            file: ./<REPLACE_WITH_ROOT_FOLDER_OF_EXECUTABLE>/veld.yaml
            service: veld
          volumes:
            - ./<REPLACE_WITH_ROOT_FOLDER_OF_MODEL>/:/veld/input/1/
            - ./<REPLACE_WITH_ROOT_FOLDER_OF_EVALUATION>/:/veld/input/2/
            - ./<REPLACE_WITH_ROOT_FOLDER_OF_REPORT>/:/veld/output/
          environment:
            model_path: "/veld/input/1/<REPLACE_WITH_RELATIVE_PATH>"
            model_metadata_path: "/veld/input/1/<REPLACE_WITH_RELATIVE_PATH_OR_NOT>"
            model_train_reproducible: "<REPLACE_OR_NOT>"
            eval_data_path: "/veld/input/2/<REPLACE_WITH_RELATIVE_PATH>"
            eval_results_folder: "/veld/output/<REPLACE_WITH_RELATIVE_PATH>"

services:
  veld:
    build: .
    volumes:
      - ./src/:/veld/executable/
    working_dir: /veld/executable/
    command: python /veld/executable/eval_and_report.py

