x-veld:
  code:

services:
  veld_eval_fasttext:
    build: 
      context: .
      dockerfile: ./build_glove.dockerfile
    command: python eval_glove.py
    volumes:
      - ./src/:/veld/code/:z
    environment:
      in_model_file: null
      in_model_metadata_file: null
      in_eval_gold_data_file: null
      out_eval_summary_file: null
      out_eval_log_file: null

