x-veld:
  executable:

    inputs:
      - volume: /veld/input/1/
        type: 
          - "word2vec model"
          - "fasttext model"
        content:
          - "NLP model"
          - "word embeddings model"
      - volume: /veld/input/2/
        type: "yaml"
        content:
          - "NLP evaluation data"
          - "NLP data"

    outputs:
      volume: /veld/output/
      type: 
        - "yaml"
        - "txt"
      content: "NLP evaluation"

    environment:
      model_path:
        path_prefix: "/veld/input/1/"
        description: "path to model file."
        type: 
          - "word2vec model"
          - "fasttext model"
      model_metadata_path:
        path_prefix: "/veld/input/1/"
        description: "path to metadata yaml file."
        type: "yaml"
      eval_data_path:
        path_prefix: "/veld/input/2/"
        description: "path to evaluation yaml file."
        type: "yaml"
      eval_results_folder:
        path_prefix: "/veld/output/"
        description: "path to folder where summary and logs will be saved to."
        type: 
          - "yaml"
          - "txt"

services:
  veld:
    build: .
    volumes:
      - ./volumes/input/1/:/veld/input/1/
      - ./volumes/input/2/:/veld/input/2/
      - ./volumes/output/:/veld/output/
      - ./src/:/veld/executable/
    working_dir: /veld/executable/
    command: python /veld/executable/eval_and_report.py
    environment:
      model_path: "/veld/input/1/<REPLACE>"
      model_metadata_path: "/veld/input/1/<REPLACE>"
      eval_data_path: "/veld/input/2/<REPLACE>"
      eval_results_folder: "/veld/output/<REPLACE>"

