x-veld:
  code:

services:
  veld_eval_glove:
    build: 
      context: .
      dockerfile: ./build_glove.dockerfile
    command: python3 eval_glove.py
    volumes:
      - ./src/:/veld/code/:z
    environment:
      in_1_vector_file: null
      model_id: null
      in_1_model_metadata_file: null
      in_2_eval_gold_data_file: null
      out_1_eval_summary_file: null
      out_2_eval_log_file: null

