x-veld:
  executable:

    inputs:
      - volume: /veld/input/1/
        type: 
          - "word2vec model"
          - "fasttext model"
        content:
          - "NLP model"
          - "word embeddings model"
      - volume: /veld/input/2/
        type: "yaml"
        content:
          - "NLP evaluation data"
          - "NLP data"

    outputs:
      volume: /veld/output/
      type: 
        - "yaml"
        - "txt"
      content: "NLP evaluation"

    environment:
      model_path:
        description: "path to model file."
        type: string
        path_prefix: "/veld/input/1/"
      model_metadata_path:
        description: "path to metadata yaml file."
        type: string
        path_prefix: "/veld/input/1/"
      eval_data_path:
        description: "path to evaluation yaml file."
        type: string
        path_prefix: "/veld/input/2/"
      eval_results_folder:
        description: "path to folder where summary and logs will be saved to."
        type: string
        path_prefix: "/veld/output/"

services:
  veld:
    build: .
    volumes:
      - ./src/:/veld/executable/
    working_dir: /veld/executable/
    command: python /veld/executable/eval_and_report.py

