x-veld:
  code:
    about:
      description: "self defined evaluation logic on word embeddings."
      topics:
        - "NLP"
        - "Machine learning"
        - "evaluation"

    inputs:
      - volume: /veld/input/1/
        file_formats: 
          - "word2vec model"
          - "word2vec model"
          - "yaml"
        contents:
          - "NLP model"
          - "word embeddings model"
          - "metadata"
      - volume: /veld/input/2/
        file_formats: "yaml"
        contents:
          - "NLP evaluation data"
          - "NLP data"

    outputs:
      volume: /veld/output/
      file_formats: 
        - "yaml"
        - "txt"
      contents:
        - "NLP evaluation score"
        - "logging"

    environment:
      model_path:
        description: "path to model file."
        type: path
        path_prefix: "/veld/input/1/"
      model_metadata_path:
        description: "path to model metadata file."
        type: path
        path_prefix: "/veld/input/1/"
      eval_data_path:
        description: "path to evaluation yaml file."
        type: path
        path_prefix: "/veld/input/2/"
      eval_results_folder:
        description: "path to folder where summary and logs will be saved to."
        type: path
        path_prefix: "/veld/output/"

services:
  veld_eval_word2vec:
    build: 
      context: .
      dockerfile: ./build_word2vec.dockerfile
    command: python eval_word2vec.py
    volumes:
      - ./src/:/veld/code/:z
    environment:
      in_1_model_file: null
      in_1_model_metadata_file: null
      in_2_eval_gold_data_file: null
      out_1_eval_summary_file: null
      out_2_eval_log_file: null

