x-veld:
  code:
    about:
      description: "self defined evaluation logic on word embeddings."
      topics:
        - "NLP"
        - "Machine learning"
        - "evaluation"

    inputs:
      - volume: /veld/input/1/
        file_formats: 
          - "word2vec model"
          - "fasttext model"
          - "yaml"
        contents:
          - "NLP model"
          - "word embeddings model"
          - "metadata"
      - volume: /veld/input/2/
        file_formats: "yaml"
        contents:
          - "NLP evaluation data"
          - "NLP data"

    outputs:
      volume: /veld/output/
      file_formats: 
        - "yaml"
        - "txt"
      contents:
        - "NLP evaluation score"
        - "logging"

    environment:
      model_path:
        description: "path to model file."
        type: path
        path_prefix: "/veld/input/1/"
      model_metadata_path:
        description: "path to model metadata file."
        type: path
        path_prefix: "/veld/input/1/"
      eval_data_path:
        description: "path to evaluation yaml file."
        type: path
        path_prefix: "/veld/input/2/"
      eval_results_folder:
        description: "path to folder where summary and logs will be saved to."
        type: path
        path_prefix: "/veld/output/"

services:
  veld:
    build: .
    command: python /veld/code/eval_and_report.py
    # TODO: check if this work dir is necessary
    working_dir: /veld/code/
    volumes:
      - ./volumes/input/1/:/veld/input/1/
      - ./volumes/input/2/:/veld/input/2/
      - ./volumes/output/:/veld/output/
      - ./src/:/veld/code/
    environment:
      model_path: null
      model_metadata_path: null
      eval_data_path: null
      eval_results_folder: null

